name: CI Test 
on: 
  push:
    branches:
      - dev
      - master

jobs:
  test:
    name: Build & Test 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y cmake gcc git
      
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DSDK_C_BUILD_TESTS=ON -DSDK_C_ENABLE_SANITIZERS=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure


